version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker-build/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - logs:/var/www/logs
    networks:
      - app-network
  php:
    build: .
    volumes:
      - ./:/var/www
    networks:
      - app-network
volumes:
  logs:
    driver: "local"